### ISSUE TITLE
Arrow buttons not responding

### ISSUE THREAD

**Issue by eros71-dev** [robertkirkman/sm64ex-coop#1]
**Describe the bug**
The arrow buttons don't seem to work.

**To Reproduce**
1. Open the game and start hosting.
2. Pause and disable the Free Camera, the Analog Cam, and Mouse Look.
3. Go back to the game.
4. Press the arrow buttons to try to move the camera around. Nothing happens.

**Expected behavior**
The camera should move around and toggle the different zoom options and the head cam.

**Screenshots**
![Screenshot_20230103-194846](https://user-images.githubusercontent.com/16540103/210422683-9a84ed15-15fa-4d47-ae5d-43c4de8deafa.png)

**Platform info:**
 - Device: Pixel 5 (Google)
 - OS: Android 13
 - Date of build: March 3rd, January 2023.
 - Latest commit, clean build.

**Additional context**
I can't confirm 100% but I think the camera was working mostly fine the last time I've compiled the game, around 4~5 days ago, before the button layout was updated.

**Comment by robertkirkman** [comment]
Hi, I'm sorry for the confusion, and I will leave this issue open until I think of some way to make a change to avoid this confusion. Those arrow buttons in the current default layout (which was requested by users for compatibility with some Lua mods) are actually bound to the actions of the **D-Pad**

![image](https://user-images.githubusercontent.com/31490854/210974242-453be95a-a40f-4927-89a8-c4351c908001.png)

and _not_ the **C-buttons**

![image](https://user-images.githubusercontent.com/31490854/210974366-c5e01147-b600-48d6-b825-ba675ce062be.png)

While the current default camera input is with Analog Mouse Look via a touchpad-like invisible rectangle in the upper right area of the touchscreen.

The real C-buttons _can_ be used with the settings you want, but they are currently disabled in the default layout via the `sm64config.txt` in a way that might be confusing for users to try changing. **I plan to try to make a GUI to allow easily fully customizing the button positions**, which should make it easier to choose the settings you want.

**Comment by robertkirkman** [comment]
OK I have now pushed the first version of my new control positions editing GUI. You can use it to achieve what you're asking for by doing as I do in this quick demo:
[touchcontrolspositioneditor.webm](https://user-images.githubusercontent.com/31490854/213015133-bc8b67a8-f473-485a-abff-ba9252946092.webm)

Please try it and tell me whether it solves this issue for you, or if the new configuration GUI is too buggy on your device to work yet.
