### ISSUE TITLE
Keyboard might not open when pressing Chat button

### ISSUE THREAD

**Issue by frog8412** [robertkirkman/sm64ex-coop#11]
**Describe the bug**
The keyboard wouldn't appear, and you won't be able to chat until you restart the game.

**To Reproduce**
1. Join any lobby
2. As soon as you load in, press the Chat button.
3. The keyboard might not appear. You can play, but you can't chat!

**Expected behavior**
The keyboard will open and you can chat.

**Screenshots**
I don't have screenshot, but i can explain it:
The textbox appears, but the Android keyboard doesn't

**Smartphone (please complete the following information):**
 - Device: Xiaomi POCO M5s
 - OS: Android 13; 2207117BPG Build/TP1A.220624.014 (from Google Chrome)
 - Browser Google Chrome
 - Version 122.0.6261.119

**Comment by robertkirkman** [comment]
Hi, thanks for telling me this. Sometimes, certain keyboard apps can have strange problems with my app. Could you try again using this keyboard app: https://f-droid.org/en/packages/org.pocketworkstation.pckeyboard/ 
Then let me know if the same thing is still happening while using that keyboard app or not?

**Comment by frog8412** [comment]
another issue related to this one: the keyboard might randomly close and don't appear
same happens with the keyboard you recommended to me

**Comment by lucastheguyy** [comment]
Normal behavior in android. Its a ram thing, when youre running low on ram the keyboard app can fail to load and be killed in order to prevent possible crashes

**Comment by frog8412** [comment]
> Normal behavior in android. Its a ram thing, when youre running low on ram the keyboard app can fail to load and be killed in order to prevent possible crashes

a
yea i was about to say its a performance issue, thx
