### ISSUE TITLE
How to install render96?

### ISSUE THREAD

**Issue by thanone2** [robertkirkman/sm64ex-coop#14]
Is it possible? if so, how would I do this?

**Comment by robertkirkman** [comment]
Hello, thanks for your question. You can do that using these commands in any supported version of Termux:
```
pkg install wget p7zip rsync
wget https://web.archive.org/web/20231228171913if_/https://sm64ex-coopmods.com/wp-content/uploads/2023/01/Render96_Chars.zip
7z x Render96_Chars.zip
mkdir -p /storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/
cp -r Render96_Chars/Render96\ Chars/ /storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/
wget https://github.com/Render96/ModelPack/releases/download/3.2/Render96_DynOs_v3.2.7z
7z x Render96_DynOs_v3.2.7z
cp -r Render96_DynOs_v3.2/ /storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/
git clone -b sm64ex-and-others https://github.com/pokeheadroom/RENDER96-HD-TEXTURE-PACK.git
rsync -r RENDER96-HD-TEXTURE-PACK/gfx /storage/emulated/0/com.owokitty.sm64excoop/dynos/packs
```
Render96 assets take up a huge amount of your phone storage, so this download will take a very long time.

Unfortunately, izzy2fancy's SM64 Builder Termux included a link in its download code for "Render96" to a domain that expired. Some of the same links in my documentation are also dead, but documentation gives me the flexibility to update the links on a case by case basis as needed and allows the users to find historical information about the mod more easily.

**Comment by thanone2** [comment]
> Hello, thanks for your question. You can do that using these commands in any supported version of Termux:
> ```
> pkg install p7zip rsync
> wget https://web.archive.org/web/20231228171913if_/https://sm64ex-coopmods.com/wp-content/uploads/2023/01/Render96_Chars.zip
> 7z x Render96_Chars.zip
> mkdir -p /storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/
> cp -r Render96_Chars/Render96\ Chars/ /storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/
> git clone -b sm64ex-and-others https://github.com/pokeheadroom/RENDER96-HD-TEXTURE-PACK.git
> rsync -r RENDER96-HD-TEXTURE-PACK/gfx /storage/emulated/0/com.owokitty.sm64excoop/dynos/packs
> ```
> Render96 assets take up a huge amount of your phone storage, so this download will take a very long time.
> 
> Unfortunately, izzy2fancy's SM64 Builder Termux included a link in its download code for "Render96" to a domain that expired. Some of the same links in my documentation are also dead, but documentation gives me the flexibility to update the links on a case by case basis as needed and allows the users to find historical information about the mod more easily.

It worked! Thanks!![Screenshot_20240514-161442_sm64ex-coop.jpg](https://github.com/robertkirkman/sm64ex-coop/assets/121321813/36166ae8-191d-4b23-9fa9-2c2e4d039bcb)
