### ISSUE TITLE
Sm64ex-coop Mobile: No sound from mods

### ISSUE THREAD

**Issue by IWasBaked** [robertkirkman/sm64ex-coop#21]
By some reason sound from mods wont play ingame, isnt working with Nexbotes; Day/Night Cycle; OMM; Custom Characters and others.

Custom sounds as reworked level background music is working well, but not the sounds

https://github.com/user-attachments/assets/99ee4671-7525-432e-b1c1-3542370d5415

**Comment by robertkirkman** [comment]
Hi please go into your Termux, get to the `~ $` screen if necessary with CTRL + C buttons,  and type these commands
```bash
cd sm64ex-coop
git log | head
```
and send the result of what you see here

**Comment by robertkirkman** [comment]
And also, could you tell me what the sound that is supposed to be playing in your video sounds like and which mod makes it?

**Comment by IWasBaked** [comment]
ingame the mod Day/Night Cycle changes background music 
the mod: https://www.youtube.com/watch?v=HuxiamEAPN0&t=32s (1:58)
and forgot to say, ive installed the game without Termux, but ill try if this gonna work

**Comment by robertkirkman** [comment]
Please install the game using [sm64ex-coop builder Termux](https://github.com/robertkirkman/termux-app/releases/download/v0.1.2/termux-app_v0.1.2+apt-android-7-github-debug_universal.apk), then send the result of the commands afterward.
If you have Android 14, use `apt-mark hold bash && yes | pkg upgrade -y` before anything else in sm64ex-coop builder Termux, then run it.

**Comment by IWasBaked** [comment]
Alr, Ive installed the game with Termux, and i see the differences now, it got fixed :)
And one question: is it possible to install DX version on mobile versions? If not, that not that bad.

Thanks for helping 👍

**Comment by robertkirkman** [comment]
> Alr, Ive installed the game with Termux, and i see the differences now, it got fixed :) And one question: is it possible to install DX version on mobile versions? If not, that not that bad.
> 
> Thanks for helping 👍

You're welcome! "sm64coopdx 1.0" has another name also which is "v37". you can follow this other issue for status updates on that https://github.com/robertkirkman/sm64ex-coop/issues/19

**Comment by Bineez** [comment]
hi, i play sm64 coop dx using portmaster port. But when using character mods such as megaman 1.2.10, there are no sound effects of the modded character.
