### ISSUE TITLE
How To Update Sm64ex Coop Into V37

### ISSUE THREAD

**Issue by CarGamerYoutuber** [robertkirkman/sm64ex-coop#22]
**Describe the bug**
Please Update Sm64ex Coop To v37 Because v36.1 Is Outdated 

**Desktop (please complete the following information):**
 - OS: [Magic Os]
 - Browser [Chrome]
 - Version [Android 13]

**Smartphone (please complete the following information):**
 - Device: [Honor x7]
 - OS: [Magic Os 7.1]
 - Browser [Chrome]
 - Version [Android 13]

**Comment by robertkirkman** [comment]
Duplicate of #19

**Comment by CarGamerYoutuber** [comment]
Tell Me

**Comment by Aust20156** [comment]
How do on tablet? (MODEL: FIRE HD 8 (10th gen) (also my OS is  Fire OS 7.3.2.9)

**Comment by Aust20156** [comment]
And my tablet is Android 7/8/9

**Comment by Aust20156** [comment]
Response yet?
