### ISSUE TITLE
Game crashes when entering castle lobby or BOB

### ISSUE THREAD

**Issue by CMDSKIDD** [robertkirkman/sm64ex-coop#24]
So, I was testing the new update of the port, but when I tried to enter the castle, the game crashed when I comed close to the sun carpet, this also happened when I tried to enter the BOB level

1. Go to castle lobby or bob
2. (Castle lobby only) come close to the sun carpet
3. (BOB only) enter the level and wait like 3 seconds
4. See error :v

I just expected that the game simply doesn't crash

**Smartphone (please complete the following information):**
 - Device: [Android A23]
 - OS: [Android]
 - Browser [chrome beta]
 - Version [Android 14]

**Comment by CMDSKIDD** [comment]
Btw, this only happens when I have the Character Select Mod (+ some skins) activated

**Comment by robertkirkman** [comment]
Right now miniaudio patch level in this repo is roughly equivalent to that of version 37, and lacks a few crash fixes introduced in version 37.1. When #19 gets a solution you can expect it to include updated miniaudio support which will help with similar problems in some mods. One mod I can confirm will have improved support is Mario Beta Voice Remastered, so the fix might also apply to your situation. If it didn't happen to you previously in 36.1 when the character select mod didn't have sounds, you can use your old `sm64.us.apk` you have saved from before. Let me know if you need the older version without mod sounds but don't know how to get it - #17 has some troubleshooting steps that can help.

**Comment by CMDSKIDD** [comment]
Okie dokie, by the way, what does this option do? (I never touched this option)
![Screenshot_20240801_005414_sm64ex-coop](https://github.com/user-attachments/assets/45793380-884b-4f31-b665-a41fe4f5f042)

**Comment by robertkirkman** [comment]
That is a special option for one person's device that person is Porcino. I believe it is necessary for when your phone has water on the screen and you can't get rid of the water.

**Comment by robertkirkman** [comment]
you can use that option even if your touchscreen works and it's just a different feeling control setting it's too complicated to explain, you just have to feel what it's like to use it.

**Comment by CMDSKIDD** [comment]
Okie dokie

**Comment by CMDSKIDD** [comment]
Just a little update, the game only crashes if I press any button that makes the character load a custom voice
