### ISSUE TITLE
Why does it generate a f3dex2e file for me?

### ISSUE THREAD

**Issue by Sphoner** [robertkirkman/sm64ex-coop#27]
I finished compiling but instead of an apk I generated an f3dex2e file

**Comment by robertkirkman** [comment]
Hi you accidentally generated the [X11 mode binary](https://github.com/robertkirkman/sm64ex-coop?tab=readme-ov-file#how-to-get-this-mode) that one is for use with the Termux:X11 app. please use these commands to switch your build back to the SurfaceFlinger Window API which uses the `.apk` package format.
```bash
pkg remove libglvnd
pkg install which
cd ~/sm64ex-coop
make distclean
make
cp build/us_pc/sm64.us.apk /storage/emulated/0/
```
If you see dependency conflicts when you try to use those commands, please let me know and there are **alternative workarounds available** that take more commands to configure. I'm sorry that you have to swap dependencies to swap build configurations, **in a future update I am going to try to fix that**.

**Comment by Sphoner** [comment]
I'll be trying it, thanks!
