### ISSUE TITLE
modding

### ISSUE THREAD

**Issue by infdevcarl** [robertkirkman/sm64ex-coop#34]
is there any way to mod sm64ex coop on android? i wanna change the hud

**Comment by robertkirkman** [comment]
Yes and there is documentation [here](https://github.com/robertkirkman/sm64ex-coop/blob/android/docs/lua/lua.md) and you can copy other people's code to change the hud and just change it until it does what you want, like this one

[![demo](https://i.ytimg.com/vi/O_1qMJQaEmk/maxresdefault.jpg)](https://www.youtube.com/watch?v=O_1qMJQaEmk "HL2 HUD")

and the mods go unzipped in `/storage/emulated/0/com.owokitty.sm64excoop/user/mods/` and theres another mods folder, but that other one is specially for the preinstalled mods and I don't recommend putting additional mods there for beginners. Your custom mods should go in the folder I mentioned first.

**Comment by infdevcarl** [comment]
i just wanna change the texture of the hud

**Comment by robertkirkman** [comment]
Here are some locations to change button textures but if you don't mean that hud then you need to send a screenshot of which hud to change.

```
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_button.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_button_dark.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_cup.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_cdown.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_cleft.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_cright.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_chat.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_up.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_down.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_left.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_right.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_lua.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_check.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_cross.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_reset.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_snap.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/touchcontrols/touch_trash.rgba16.png
/storage/emulated/0/com.owokitty.sm64excoop/dynos/packs/gfx/textures/segment2/segment2.04400.rgba16.png
```
https://github.com/robertkirkman/sm64ex-coop/tree/android/textures/touchcontrols

Here are 2 video guides of 2 methods to do it. **The first method is much easier**. the second method is currently only necessary for changing **X letter and Z letter textures** and a couple of other obscure ones in version 36.1. in version 37+ all textures will be editable using the first video's method.


#### Example of editing a texture using DynOS
[![demo](https://i.ytimg.com/vi/vjYdVNGRcPg/maxresdefault.jpg)](https://youtu.be/vjYdVNGRcPg?si=p4zabVdtmG6w95qY&t=117 "with dynos")

#### Example of editing a texture without using DynOS
[![demo](https://i.ytimg.com/vi/n1BW8qMEvW0/maxresdefault.jpg)](https://www.youtube.com/watch?v=n1BW8qMEvW0 "non dynos")

**Comment by infdevcarl** [comment]
what i meant was like the hud in mario 64 not touchscreen buttons

**Comment by robertkirkman** [comment]
> what i meant was like the hud in mario 64 not touchscreen buttons

ok then yes that's changed by this mod as an example, the one I sent first

[![demo](https://i.ytimg.com/vi/O_1qMJQaEmk/maxresdefault.jpg)](https://www.youtube.com/watch?v=O_1qMJQaEmk "HL2 HUD")

**Comment by infdevcarl** [comment]
alr

**Comment by robertkirkman** [comment]
Also you can look at this folder of the Render96 texture pack if you want to see what textures you can change in the normal HUD, and to make your own textures for those numbers and symbols in the normal HUD you can just install the Render96 texture pack using [these directions ](https://github.com/robertkirkman/sm64ex-coop/issues/14#issuecomment-2110000502) and then use a picture editor app to edit the pictures and put your own pictures in on top of the Render96 ones.


https://github.com/pokeheadroom/RENDER96-HD-TEXTURE-PACK/blob/sm64ex-and-others/gfx/textures/segment2/segment2.00000.rgba16.png
