### ISSUE TITLE
b3313 crashing

### ISSUE THREAD

**Issue by infdevcarl** [robertkirkman/sm64ex-coop#35]
how do i play b3313 it keeps crashing for some reason, i have a good phone

**Comment by robertkirkman** [comment]
Hi did you download the game using [sm64ex-coop builder Termux](https://github.com/robertkirkman/termux-app/releases/download/v0.1.2/termux-app_v0.1.2+apt-android-7-github-debug_universal.apk)?

**Comment by infdevcarl** [comment]
yes

**Comment by robertkirkman** [comment]
I'm unable to reproduce that, sorry. The app doesn't close on my phone when playing B3313 v0.7 update 8.

**Comment by infdevcarl** [comment]
can you send me the b3313 you are using?

**Comment by robertkirkman** [comment]
You can find it somewhere on one of the B3313 discord servers and you can find that from one of the channels on the discord server "coop central"

**Comment by infdevcarl** [comment]
alright
