### ISSUE TITLE
Its not showing the things i need

### ISSUE THREAD

**Issue by Chickencoop2305** [robertkirkman/sm64ex-coop#5]
I followed it perfectly there was no E or anything else
I entered pkg upgrade and that didn't show what it was supposed to so I entered pkg upgrade -y and it STILL didn't word so I copy pasted what it Said to put in and it STILL didn't work I entered I [SHIFT I and enter] but it said command didn't exist can I have help?
BTW I can't add a screenshot for some reason

**Comment by robertkirkman** [comment]
Hello **If you are trying to follow `README_android.md` and you are struggling, I recommend to uninstall normal Termux and install this: [sm64ex-coop builder Termux](https://github.com/robertkirkman/termux-app/releases/download/v0.1.2/termux-app_v0.1.2+apt-android-7-github-debug_universal.apk).** With that, **you don't have to type _any_ commands.**

**Comment by Chickencoop2305** [comment]
Thanks I didn't expect you to respond
