### ISSUE TITLE
Textures are missing 

### ISSUE THREAD

**Issue by Someone8877** [robertkirkman/sm64ex-coop#9]
**Describe the bug**
So I compiled version 36.1 of sm64ex-coop on my 32-bit phone and when I got to Bob-omb battlefield textures were missing

![Screenshot_20240119-124001_sm64ex-coop](https://github.com/robertkirkman/sm64ex-coop/assets/110671196/972e2768-c4ad-46a9-869b-ff598fa63b2d)

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy J4+] 
 - OS: [Android]
 - Browser [Kiwi Browser]
 - Version [Android 9]

**Comment by robertkirkman** [comment]
Hello, I have Samsung Galaxy S III (32-bit) and Samsung Galaxy S II Epic 4G Touch (32-bit) and that doesn't happen to me. Please try backing up the `com.owokitty.sm64excoop` folder to a different folder, then deleting the original  one from the active location (`/storage/emulated/0`), then open the game again. If this is still happening after you test that, please test with a texture pack enabled and tell me whether the same thing happens regardless of texture pack.

**Comment by Someone8877** [comment]
I took the folder and put it in the downloads folder and the game made a new one but it was still the same when I tried render96 it had the same thing

![Screenshot_20240121-072727_sm64ex-coop.jpg](https://github.com/robertkirkman/sm64ex-coop/assets/110671196/11e42fd7-15b9-4aed-bc6a-705ec61273f1)

**Comment by robertkirkman** [comment]
That's the Render96 Model Pack not the Render96 Texture Pack which you can install by using these commands
```bash
pkg install rsync
mkdir -p /storage/emulated/0/com.owokitty.sm64excoop/dynos/packs
git clone -b sm64ex-and-others https://github.com/pokeheadroom/RENDER96-HD-TEXTURE-PACK.git
rsync -r RENDER96-HD-TEXTURE-PACK/gfx /storage/emulated/0/com.owokitty.sm64excoop/dynos/packs
```

**Comment by Someone8877** [comment]
I already installed both when I showed that 2nd screenshot

**Comment by robertkirkman** [comment]
The Render96 Texture Pack is not enabled in the screenshot because the grass and letter A remain the vanilla resolution

**Comment by Someone8877** [comment]
It just says "CANNOT LINK EXECUTABLE "rsync": cannot locate symbol "locale_charset" referenced by "/data/data/com.termux/files/usr/bin/rsync"..." 

![Screenshot_20240123-180359_Termux.jpg](https://github.com/robertkirkman/sm64ex-coop/assets/110671196/1c1c76a3-6bad-460b-9721-ff2f0e46cc38)

**Comment by izzy2fancy** [comment]
> It just says "CANNOT LINK EXECUTABLE "rsync": cannot locate symbol "locale_charset" referenced by "/data/data/com.termux/files/usr/bin/rsync"..."
> 
> ![Screenshot_20240123-180359_Termux.jpg](https://private-user-images.githubusercontent.com/110671196/299012226-1c1c76a3-6bad-460b-9721-ff2f0e46cc38.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjkxNzEsIm5iZiI6MTcwNjAyODg3MSwicGF0aCI6Ii8xMTA2NzExOTYvMjk5MDEyMjI2LTFjMWM3NmEzLTZiYWQtNDYwYi05NzIxLWZmMmYwZTQ2Y2MzOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNjU0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmUxOWM5YTJhMTkwMjFmMDVjNjE5OTIzZjk2NGUwNjlmYzFhZTYyZDYxNzlkOTM1MzAzZTAxYzEzNzk5MjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wWpVwQhsYi2xru-SqKBXhu1mToOCJWUyEH1aac2PO3w)

Looks like the mirrors are bad? You have 67 not updated pkgs. Try changing your mirror. Or do you have an internet problem?

**Comment by robertkirkman** [comment]
It means that you uninstalled and reinstalled Termux in between the time that you compiled the game and pasted my commands. You must now use `yes | pkg upgrade -y` and wait, then try again after.

**Comment by Someone8877** [comment]
I used the auto builder to build the app and uninstalled it because of storage reasons

Ok it actually worked and now the texture pack works but uh it's the same

![Untitled28_20240124074446.png](https://github.com/robertkirkman/sm64ex-coop/assets/110671196/26a131e1-52a7-43e1-b317-9253180fdf94)

(For some reason when I tried to get in the painting my phone restarted and I couldn't screenshot anymore when I was in Bob-omb battlefield)

**Comment by robertkirkman** [comment]
Ok thank you. I don't know how to fix that rendering bug, but I have heard of my app triggering other devices to shut down and restart and determined that is a device problem, because on fully functioning devices, no apps are able to do that without either having root or showing the power off onscreen menu.
